version: '3.3'


services:
    rabbitmq:
        image: rabbitmq:3.8-management-alpine
        container_name: "rabbitmq"
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
            - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=password
        ports:
            - "5672:5672"


    email_sender:
        container_name: "email_sender"
        build:
            context: .
        volumes:
            - ./:/notifier
        env_file:
          - .env
